import './globals.scss'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <script
          dangerouslySetInnerHTML={{
            __html: `document.body.class = ((document.body.class) ? document.body.class + ' js-enabled' :
          'js-enabled');`,
          }}
        />
        <>
          {/* TODO: Header Component Here */}
          <div className="govuk-width-container">
            <main className="govuk-main-wrapper" role="main">
              {children}
            </main>
          </div>
          {/* TODO: Footer Component Here */}
        </>
      </body>
    </html>
  )
}
