process.env.CONTENTFUL_SPACE_ID = 'TEST_SPACE_ID'
process.env.CONTENTFUL_ACCESS_TOKEN = 'TEST_ACCESS_TOKEN'
process.env.CONTENTFUL_PREVIEW_MODE = 1
process.env.CONTENTFUL_PREVIEW_ACCESS_TOKEN = 'TEST_PREVIEW_ACCESS_TOKEN'
process.env.CONTENTFUL_MANAGEMENT_ACCESS_TOKEN = 'TEST_MANAGEMENT_ACCESS_TOKEN'
process.env.CONTENTFUL_ENVIRONMENT = 'dev'
process.env.NEXT_REVALIDATE_TIME = 60
